import '../styles/_navigation.scss';
import type { Metadata } from 'next'
import { Genos,Anybody } from 'next/font/google'

import { AiOutlineShoppingCart } from "react-icons/ai";


export const metadata: Metadata = {
  title: 'My Next Blog Post',
  description: 'Generated by create next app',
}

const genos = Genos({ 
  subsets: ['latin'],
  weight:'400'
 })
const anybody = Anybody({ 
  subsets: ['latin'],
  weight:'400'
 })


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${genos.className} ${anybody.className}`}>
        <nav className='navbar'>
          <div className='logo'>
            <p className='logo-main-text'>electrify</p>
            <p className='logo-text'>by rentals</p>
          </div>
          <ul className="nav-ul">
            <li>
              <a href="#my-element" >Home</a>
            </li>
            <li>
            <a href="#my-element" >How it works</a>
            </li>
            <li>
            <a href="#my-element" >Charging</a>
            </li>
            <li>
              <a href="#my-element" >Vehicles</a>
            </li>
          </ul>
          <div className='login'>
            <button className="my-button"><AiOutlineShoppingCart style={{ fontSize: '20px', margin:'0 5px 0 0px' }} /> MY CARD</button>
            <button className="login-button">LOGIN</button>
          </div>

        </nav>
        {children}
      </body>
    </html>
  )
}
